# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "ini-0.1.0-YCQ9Ys0pAABixEvvQvhVXAdqRE3wrZk_wiL9TPNHhB8d";
    path = fetchgit {
      url = "https://github.com/ziglibs/ini.git";
      rev = "918f16d0dcf893d0c1cdffe204faa08bb3584e04";
      hash = "sha256-4o4tFV05IV/uSQWDtwqaeStY46ORmze//2IlBQ5MhnY=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJv3LAAABBRVoZWVrKZdyLoUfl5VRY5fqRRRdnF5L";
    path = fetchgit {
      url = "https://github.com/ziglibs/known-folders.git";
      rev = "83d39161eac2ed6f37ad3cb4d9dd518696ce90bb";
      hash = "sha256-faXaYD+0oe6M9iB4m46O6djWxXuuluNJeJdpIXNj8DM=";
    };
  }
  {
    name = "wayland-0.4.0-lQa1khbMAQAsLS2eBR7M5lofyEGPIbu2iFDmoz8lPC27";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.4.0.tar.gz";
      hash = "sha256-ulIII5iJpM/W/VJB0HcdktEO2eb9T9J0ln2A1Z94dU4=";
    };
  }
  {
    name = "xkbcommon-0.3.0-VDqIe3K9AQB2fG5ZeRcMC9i7kfrp5m2rWgLrmdNn9azr";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.3.0.tar.gz";
      hash = "sha256-e5bPEfxl4SQf0cqccLt/py1KOW1+Q1+kWZUEXBbh9oQ=";
    };
  }
]
